
// aux
const AUX_RANGE_START_LETTER = charAfter('A', INSTERTED_COLUMNS_NUMBER)
const AUX_RANGE_END_LETTER = charAfter('E', INSTERTED_COLUMNS_NUMBER)
const AUX_RANGE_START_ROW = 34
const AUX_RANGE_END_ROW = 40
const AUX_RANGE_TEXT = AUX_RANGE_START_LETTER + AUX_RANGE_START_ROW.toString() + ":" + AUX_RANGE_END_LETTER + AUX_RANGE_END_ROW.toString()

const AUX_SAVINGS_RANGE_START_LETTER = charAfter('D', INSTERTED_COLUMNS_NUMBER)
const AUX_SAVINGS_RANGE_END_LETTER = charAfter('E', INSTERTED_COLUMNS_NUMBER)
const AUX_SAVINGS_RANGE_START_ROW = 34
const AUX_SAVINGS_RANGE_END_ROW = 36
const AUX_DAILY_BUDGET_ROW = 37
 
const AUX_ESTIMATED_SAVINGS_RANGE_TEXT = AUX_SAVINGS_RANGE_END_LETTER + AUX_SAVINGS_RANGE_START_ROW.toString()

const AUX_SAVINGS_RANGE_TEXT = AUX_SAVINGS_RANGE_START_LETTER + AUX_SAVINGS_RANGE_START_ROW.toString() + ":" + AUX_SAVINGS_RANGE_END_LETTER + AUX_SAVINGS_RANGE_END_ROW.toString()

const AUX_SAVINGS_HEADER_RANGE_TEXT = AUX_RANGE_START_LETTER + AUX_SAVINGS_RANGE_START_ROW.toString()


const DEFAULT_DAILY_BUDGET_CELL_TEXT = AUX_SAVINGS_RANGE_START_LETTER + AUX_DAILY_BUDGET_ROW.toString()