const DAILY__DATE_LETTER =                      charAfter('O', INSTERTED_COLUMNS_NUMBER)
const DAILY__EXPENSE_INCLUDING_PLANNED_LETTER = charAfter('P', INSTERTED_COLUMNS_NUMBER)
const DAILY__EXPENSE_EXCLUDING_PLANNED_LETTER = charAfter('Q', INSTERTED_COLUMNS_NUMBER)
const DAILY__INCOME_LETTER =                    charAfter('R', INSTERTED_COLUMNS_NUMBER)
const DAILY__TRANSFER_LETTER =                  charAfter('S', INSTERTED_COLUMNS_NUMBER)
const DAILY__DAILY_BUDGET_LETTER =              charAfter('T', INSTERTED_COLUMNS_NUMBER)
const DAILY__DAILY_BALANCE_LETTER =             charAfter('U', INSTERTED_COLUMNS_NUMBER)

const DAILY__DATE_RANGE_TEXT =                      getDailySingleColumnRangeText(DAILY__DATE_LETTER)
const DAILY__EXPENSE_INCLUDING_PLANNED_RANGE_TEXT = getDailySingleColumnRangeText(DAILY__EXPENSE_INCLUDING_PLANNED_LETTER)
const DAILY__EXPENSE_EXCLUDING_PLANNED_RANGE_TEXT = getDailySingleColumnRangeText(DAILY__EXPENSE_EXCLUDING_PLANNED_LETTER)
const DAILY__INCOME_RANGE_TEXT =                    getDailySingleColumnRangeText(DAILY__INCOME_LETTER)
const DAILY__TRANSFER_RANGE_TEXT =                  getDailySingleColumnRangeText(DAILY__TRANSFER_LETTER)
const DAILY__DAILY_BUDGET_RANGE_TEXT =              getDailySingleColumnRangeText(DAILY__DAILY_BUDGET_LETTER)
const DAILY__DAILY_BALANCE_RANGE_TEXT =             getDailySingleColumnRangeText(DAILY__DAILY_BALANCE_LETTER)

const DAILY__BUDGET_AND_BALANCE_RANGE_TEXT = getDailyRangeText(DAILY__DAILY_BUDGET_LETTER, DAILY__DAILY_BALANCE_LETTER)

// offsets and positions
// daily statistics table values positions (0-based)
const DAILY__DATE_POS = 0
const DAILY__EXPENSE_INCLUDING_PLANNED_POS = 1
const DAILY__EXPENSE_EXCLUDING_PLANNED_POS = 2
const DAILY__INCOME_POS =                    3
const DAILY__TRANSFER_POS =                  4
const DAILY__DAILY_BUDGET_POS =              5
const DAILY__DAILY_BALANCE_POS =             6

// offsets from date
const DAILY__EXPENSE_INCLUDING_PLANNED_OFFSET_FROM_DATE = DAILY__EXPENSE_INCLUDING_PLANNED_POS - DAILY__DATE_POS // 1
const DAILY__EXPENSE_EXCLUDING_PLANNED_OFFSET_FROM_DATE = DAILY__EXPENSE_EXCLUDING_PLANNED_POS - DAILY__DATE_POS // 2
const DAILY__INCOME_OFFSET_FROM_DATE =                    DAILY__INCOME_POS                    - DAILY__DATE_POS // 3
const DAILY__TRANSFER_OFFSET_FROM_DATE =                  DAILY__TRANSFER_POS                  - DAILY__DATE_POS // 4
const DAILY__DAILY_BUDGET_OFFSET_FROM_DATE =              DAILY__DAILY_BUDGET_POS              - DAILY__DATE_POS // 5
const DAILY__DAILY_BALANCE_OFFSET_FROM_DATE =             DAILY__DAILY_BALANCE_POS             - DAILY__DATE_POS // 6
