const TINKOFF__IS_PLANNED_HEADER_RANGE_TEXT =                     getHeaderRangeText(TINKOFF__IS_PLANNED_LETTER)
const TINKOFF__OPERATION_DATE_HEADER_RANGE_TEXT =                 getHeaderRangeText(TINKOFF__OPERATION_DATE_LETTER)
const TINKOFF__PAYMENT_DATE_HEADER_RANGE_TEXT =                   getHeaderRangeText(TINKOFF__PAYMENT_DATE_LETTER)
const TINKOFF__CARD_NUMBER_HEADER_RANGE_TEXT =                    getHeaderRangeText(TINKOFF__CARD_NUMBER_LETTER)
const TINKOFF__STATUS_HEADER_RANGE_TEXT =                         getHeaderRangeText(TINKOFF__STATUS_LETTER)
const TINKOFF__OPERATION_AMOUNT_HEADER_RANGE_TEXT =               getHeaderRangeText(TINKOFF__OPERATION_AMOUNT_LETTER)
const TINKOFF__OPERATION_CURRENCY_HEADER_RANGE_TEXT =             getHeaderRangeText(TINKOFF__OPERATION_CURRENCY_LETTER)
const TINKOFF__PAYMENT_AMOUNT_HEADER_RANGE_TEXT =                 getHeaderRangeText(TINKOFF__PAYMENT_AMOUNT_LETTER)
const TINKOFF__PAYMENT_CURRENCY_HEADER_RANGE_TEXT =               getHeaderRangeText(TINKOFF__PAYMENT_CURRENCY_LETTER)
const TINKOFF__CASHBACK_HEADER_RANGE_TEXT =                       getHeaderRangeText(TINKOFF__CASHBACK_LETTER)
const TINKOFF__CATEGORY_HEADER_RANGE_TEXT =                       getHeaderRangeText(TINKOFF__CATEGORY_LETTER)
const TINKOFF__MCC_HEADER_RANGE_TEXT =                            getHeaderRangeText(TINKOFF__MCC_LETTER)
const TINKOFF__DESCRIPTION_HEADER_RANGE_TEXT =                    getHeaderRangeText(TINKOFF__DESCRIPTION_LETTER)
const TINKOFF__BONUS_INCLUDING_CACHBACK_HEADER_RANGE_TEXT =       getHeaderRangeText(TINKOFF__BONUS_INCLUDING_CACHBACK_LETTER)
const TINKOFF__INVEST_ROUNDING_HEADER_RANGE_TEXT =                getHeaderRangeText(TINKOFF__INVEST_ROUNDING_LETTER)
const TINKOFF__OPERATION_AMOUNT_WITH_ROUNDING_HEADER_RANGE_TEXT = getHeaderRangeText(TINKOFF__OPERATION_AMOUNT_WITH_ROUNDING_LETTER)
const TINKOFF__DEFINED_OPERATION_TYPE_HEADER_RANGE_TEXT =         getHeaderRangeText(TINKOFF__OPERATION_TYPE_LETTER)
const TINKOFF__MY_CATEGORY_HEADER_RANGE_TEXT =                    getHeaderRangeText(TINKOFF__MY_CATEGORY_LETTER)
const TINKOFF__MANUAL_EDITING_INFO_HEADER_RANGE_TEXT =            getHeaderRangeText(TINKOFF__MANUAL_EDITING_INFO_LETTER)
const TINKOFF__COMMENT_HEADER_RANGE_TEXT =                        getHeaderRangeText(TINKOFF__COMMENT_LETTER)

const TINKOFF_HEADERS_RANGE_TEXTS_LIST = [
  TINKOFF__IS_PLANNED_HEADER_RANGE_TEXT,
  TINKOFF__OPERATION_DATE_HEADER_RANGE_TEXT,
  TINKOFF__PAYMENT_DATE_HEADER_RANGE_TEXT,
  TINKOFF__CARD_NUMBER_HEADER_RANGE_TEXT,
  TINKOFF__STATUS_HEADER_RANGE_TEXT,
  TINKOFF__OPERATION_AMOUNT_HEADER_RANGE_TEXT,
  TINKOFF__OPERATION_CURRENCY_HEADER_RANGE_TEXT,
  TINKOFF__PAYMENT_AMOUNT_HEADER_RANGE_TEXT,
  TINKOFF__PAYMENT_CURRENCY_HEADER_RANGE_TEXT,
  TINKOFF__CASHBACK_HEADER_RANGE_TEXT,
  TINKOFF__CATEGORY_HEADER_RANGE_TEXT,
  TINKOFF__MCC_HEADER_RANGE_TEXT,
  TINKOFF__DESCRIPTION_HEADER_RANGE_TEXT,
  TINKOFF__BONUS_INCLUDING_CACHBACK_HEADER_RANGE_TEXT,
  TINKOFF__INVEST_ROUNDING_HEADER_RANGE_TEXT,
  TINKOFF__OPERATION_AMOUNT_WITH_ROUNDING_HEADER_RANGE_TEXT,
  TINKOFF__DEFINED_OPERATION_TYPE_HEADER_RANGE_TEXT,
  TINKOFF__MY_CATEGORY_HEADER_RANGE_TEXT,
  TINKOFF__MANUAL_EDITING_INFO_HEADER_RANGE_TEXT,
  TINKOFF__COMMENT_HEADER_RANGE_TEXT
]
