const INSTERTED_COLUMNS_NUMBER = 0
const INSTERTED_COLUMN_LETTER = 'I'
 
// all sheet
const SHEET_START_LETTER = charAfter('A', INSTERTED_COLUMNS_NUMBER)
const SHEET_END_LETTER =   charAfter('AX', INSTERTED_COLUMNS_NUMBER)


const ALL_SHEET_VALUES_RANGE_TEXT = getDataRangeText(SHEET_START_LETTER, SHEET_END_LETTER)

// aux
const AUX_RANGE_START_LETTER = charAfter('A', INSTERTED_COLUMNS_NUMBER)
const AUX_RANGE_END_LETTER = charAfter('E', INSTERTED_COLUMNS_NUMBER)
const AUX_RANGE_START_ROW = 34
const AUX_RANGE_END_ROW = 39
const AUX_RANGE_TEXT = AUX_RANGE_START_LETTER + AUX_RANGE_START_ROW.toString() + ":" + AUX_RANGE_END_LETTER + AUX_RANGE_END_ROW.toString()

const AUX_SAVINGS_RANGE_START_LETTER = charAfter('D', INSTERTED_COLUMNS_NUMBER)
const AUX_SAVINGS_RANGE_END_LETTER = charAfter('E', INSTERTED_COLUMNS_NUMBER)
const AUX_SAVINGS_RANGE_START_ROW = 34
const AUX_SAVINGS_RANGE_END_ROW = 35
 
const AUX_ESTIMATED_SAVINGS_RANGE_TEXT = AUX_SAVINGS_RANGE_END_LETTER + AUX_SAVINGS_RANGE_START_ROW.toString()

const AUX_SAVINGS_RANGE_TEXT = AUX_SAVINGS_RANGE_START_LETTER + AUX_SAVINGS_RANGE_START_ROW.toString() + ":" + AUX_SAVINGS_RANGE_END_LETTER + AUX_SAVINGS_RANGE_END_ROW.toString()

const AUX_SAVINGS_HEADER_RANGE_TEXT = AUX_RANGE_START_LETTER + AUX_SAVINGS_RANGE_START_ROW.toString()

const FONT = "Verdana"
