const OTHER__IS_PLANNED_LETTER =     charAfter('AR', INSTERTED_COLUMNS_NUMBER)
const OTHER__DATE_LETTER =           charAfter('AS', INSTERTED_COLUMNS_NUMBER)
const OTHER__AMOUNT_LETTER =         charAfter('AT', INSTERTED_COLUMNS_NUMBER)
const OTHER__OPERATION_TYPE_LETTER = charAfter('AU', INSTERTED_COLUMNS_NUMBER)
const OTHER__MY_CATEGORY_LETTER =    charAfter('AV', INSTERTED_COLUMNS_NUMBER)
const OTHER__COMMENT_LETTER =        charAfter('AW', INSTERTED_COLUMNS_NUMBER)

const OTHER__FIRST_COLUMN_LETTER = OTHER__IS_PLANNED_LETTER
const OTHER__LAST_COLUMN_LETTER = OTHER__COMMENT_LETTER

const OTHER__DATA_RANGE_TEXT =                           getDataRangeText(OTHER__FIRST_COLUMN_LETTER, OTHER__LAST_COLUMN_LETTER)
const OTHER__DATA_WITHOUT_ISPLANNED_RANGE_TEXT =         getDataRangeText(OTHER__DATE_LETTER, OTHER__LAST_COLUMN_LETTER)

const OTHER__DATE_RANGE_TEXT =                           getDataRangeText(OTHER__DATE_LETTER, OTHER__DATE_LETTER)
const OTHER__OPERATION_TYPE_RANGE_TEXT =                 getDataRangeText(OTHER__OPERATION_TYPE_LETTER, OTHER__OPERATION_TYPE_LETTER)
const OTHER__OPERATION_TYPE_AND_MY_CATEGORY_RANGE_TEXT = getDataRangeText(OTHER__OPERATION_TYPE_LETTER, OTHER__MY_CATEGORY_LETTER)


// offsets and positions
// Other data table values positions (0-based)
const OTHER__IS_PLANNED_POS =     0
const OTHER__DATE_POS =           1
const OTHER__AMOUNT_POS =         2
const OTHER__OPERATION_TYPE_POS = 3
const OTHER__MY_CATEGORY_POS =    4
const OTHER__COMMENT_POS =        5

// offsets from date
const OTHER__IS_PLANNED_OFFSET_FROM_DATE =     OTHER__IS_PLANNED_POS     - OTHER__DATE_POS // -1
const OTHER__DATE_OFFSET_FROM_DATE =           OTHER__DATE_POS           - OTHER__DATE_POS //  0
const OTHER__AMOUNT_OFFSET_FROM_DATE =         OTHER__AMOUNT_POS         - OTHER__DATE_POS //  1
const OTHER__OPERATION_TYPE_OFFSET_FROM_DATE = OTHER__OPERATION_TYPE_POS - OTHER__DATE_POS //  2
const OTHER__MY_CATEGORY_OFFSET_FROM_DATE =    OTHER__MY_CATEGORY_POS    - OTHER__DATE_POS //  3
const OTHER__COMMENT_OFFSET_FROM_DATE =        OTHER__COMMENT_POS        - OTHER__DATE_POS //  4

// offsets from amount
const OTHER__IS_PLANNED_OFFSET_FROM_AMOUNT =     OTHER__IS_PLANNED_POS     - OTHER__AMOUNT_POS // -2
const OTHER__DATE_OFFSET_FROM_AMOUNT =           OTHER__DATE_POS           - OTHER__AMOUNT_POS // -1
const OTHER__AMOUNT_OFFSET_FROM_AMOUNT =         OTHER__AMOUNT_POS         - OTHER__AMOUNT_POS //  0
const OTHER__OPERATION_TYPE_OFFSET_FROM_AMOUNT = OTHER__OPERATION_TYPE_POS - OTHER__AMOUNT_POS //  1
const OTHER__MY_CATEGORY_OFFSET_FROM_AMOUNT =    OTHER__MY_CATEGORY_POS    - OTHER__AMOUNT_POS //  2
const OTHER__COMMENT_OFFSET_FROM_AMOUNT =        OTHER__COMMENT_POS        - OTHER__AMOUNT_POS //  3

// offsets from 'operation type'
const OTHER__IS_PLANNED_OFFSET_FROM_OPERATION_TYPE =     OTHER__IS_PLANNED_POS     - OTHER__OPERATION_TYPE_POS // -3
const OTHER__DATE_OFFSET_FROM_OPERATION_TYPE =           OTHER__DATE_POS           - OTHER__OPERATION_TYPE_POS // -2
const OTHER__AMOUNT_OFFSET_FROM_OPERATION_TYPE =         OTHER__AMOUNT_POS         - OTHER__OPERATION_TYPE_POS // -1
const OTHER__OPERATION_TYPE_OFFSET_FROM_OPERATION_TYPE = OTHER__OPERATION_TYPE_POS - OTHER__OPERATION_TYPE_POS //  0
const OTHER__MY_CATEGORY_OFFSET_FROM_OPERATION_TYPE =    OTHER__MY_CATEGORY_POS    - OTHER__OPERATION_TYPE_POS //  1
const OTHER__COMMENT_OFFSET_FROM_OPERATION_TYPE =        OTHER__COMMENT_POS        - OTHER__OPERATION_TYPE_POS //  2

// offsets from 'my category'
const OTHER__IS_PLANNED_OFFSET_FROM_MY_CATEGORY =     OTHER__IS_PLANNED_POS     - OTHER__MY_CATEGORY_POS // -4
const OTHER__DATE_OFFSET_FROM_MY_CATEGORY =           OTHER__DATE_POS           - OTHER__MY_CATEGORY_POS // -3
const OTHER__AMOUNT_OFFSET_FROM_MY_CATEGORY =         OTHER__AMOUNT_POS         - OTHER__MY_CATEGORY_POS // -2
const OTHER__OPERATION_TYPE_OFFSET_FROM_MY_CATEGORY = OTHER__OPERATION_TYPE_POS - OTHER__MY_CATEGORY_POS // -1
const OTHER__MY_CATEGORY_OFFSET_FROM_MY_CATEGORY =    OTHER__MY_CATEGORY_POS    - OTHER__MY_CATEGORY_POS //  0
const OTHER__COMMENT_OFFSET_FROM_MY_CATEGORY =        OTHER__COMMENT_POS        - OTHER__MY_CATEGORY_POS //  1

// offsets from comment
const OTHER__IS_PLANNED_OFFSET_FROM_COMMENT =     OTHER__IS_PLANNED_POS     - OTHER__COMMENT_POS // -5
const OTHER__DATE_OFFSET_FROM_COMMENT =           OTHER__DATE_POS           - OTHER__COMMENT_POS // -4
const OTHER__AMOUNT_OFFSET_FROM_COMMENT =         OTHER__AMOUNT_POS         - OTHER__COMMENT_POS // -3
const OTHER__OPERATION_TYPE_OFFSET_FROM_COMMENT = OTHER__OPERATION_TYPE_POS - OTHER__COMMENT_POS // -2
const OTHER__MY_CATEGORY_OFFSET_FROM_COMMENT =    OTHER__MY_CATEGORY_POS    - OTHER__COMMENT_POS // -1
const OTHER__COMMENT_OFFSET_FROM_COMMENT =        OTHER__COMMENT_POS        - OTHER__COMMENT_POS //  0


function getOffsetsFromDate(): number[] {
  return [
    OTHER__IS_PLANNED_OFFSET_FROM_DATE,
    OTHER__DATE_OFFSET_FROM_DATE ,
    OTHER__AMOUNT_OFFSET_FROM_DATE,
    OTHER__OPERATION_TYPE_OFFSET_FROM_DATE,
    OTHER__MY_CATEGORY_OFFSET_FROM_DATE,
    OTHER__COMMENT_OFFSET_FROM_DATE,
  ]
}

function getOffsetsFromAmount(): number[] {
  return [
    OTHER__IS_PLANNED_OFFSET_FROM_AMOUNT,
    OTHER__DATE_OFFSET_FROM_AMOUNT,
    OTHER__AMOUNT_OFFSET_FROM_AMOUNT,
    OTHER__OPERATION_TYPE_OFFSET_FROM_AMOUNT,
    OTHER__MY_CATEGORY_OFFSET_FROM_AMOUNT,
    OTHER__COMMENT_OFFSET_FROM_AMOUNT,
  ]
}

function getOffsetsFromOperationType(): number[] {
  return [
    OTHER__IS_PLANNED_OFFSET_FROM_OPERATION_TYPE,
    OTHER__DATE_OFFSET_FROM_OPERATION_TYPE,
    OTHER__AMOUNT_OFFSET_FROM_OPERATION_TYPE,
    OTHER__OPERATION_TYPE_OFFSET_FROM_OPERATION_TYPE,
    OTHER__MY_CATEGORY_OFFSET_FROM_OPERATION_TYPE,
    OTHER__COMMENT_OFFSET_FROM_OPERATION_TYPE,
  ]
}

function getOffsetsFromMyCategory(): number[] {
  return [
    OTHER__IS_PLANNED_OFFSET_FROM_MY_CATEGORY,
    OTHER__DATE_OFFSET_FROM_MY_CATEGORY,
    OTHER__AMOUNT_OFFSET_FROM_MY_CATEGORY,
    OTHER__OPERATION_TYPE_OFFSET_FROM_MY_CATEGORY,
    OTHER__MY_CATEGORY_OFFSET_FROM_MY_CATEGORY,
    OTHER__COMMENT_OFFSET_FROM_MY_CATEGORY,
  ]
}

function getOffsetsFromComment(): number[] {
  return [
    OTHER__IS_PLANNED_OFFSET_FROM_COMMENT,
    OTHER__DATE_OFFSET_FROM_COMMENT,
    OTHER__AMOUNT_OFFSET_FROM_COMMENT,
    OTHER__OPERATION_TYPE_OFFSET_FROM_COMMENT,
    OTHER__MY_CATEGORY_OFFSET_FROM_COMMENT,
    OTHER__COMMENT_OFFSET_FROM_COMMENT,
  ]
}

// util
function getOtherDataIsPlanned(otherDataValues: any[]): boolean {
  return asBoolean(otherDataValues[OTHER__IS_PLANNED_POS])
}
  
function getOtherDataDate(otherDataValues: any[]): any {
  return otherDataValues[OTHER__DATE_POS]
}
  
function getOtherDataAmount(otherDataValues: any[]): any {
  return otherDataValues[OTHER__AMOUNT_POS]
}
  
function getOtherDataOperationType(otherDataValues: any[]): any {
  return otherDataValues[OTHER__OPERATION_TYPE_POS]
}
  
function getOtherDataMyCategory(otherDataValues: any[]): any {
  return otherDataValues[OTHER__MY_CATEGORY_POS]
}
  
function getOtherDataMyComment(otherDataValues: any[]): any {
  return otherDataValues[OTHER__COMMENT_POS]
}
  
  