const MONTHLY__ESTIMATED_INCOMES_KEYS_LETTER =      charAfter('A',  INSTERTED_COLUMNS_NUMBER)
const MONTHLY__ESTIMATED_INCOMES_VALUES_LETTER =    charAfter('B',  INSTERTED_COLUMNS_NUMBER)
  
const MONTHLY__ACTUAL_INCOMES_KEYS_LETTER =         charAfter('D',  INSTERTED_COLUMNS_NUMBER)
const MONTHLY__ACTUAL_INCOMES_VALUES_LETTER =       charAfter('E',  INSTERTED_COLUMNS_NUMBER)
  
const MONTHLY__ESTIMATED_EXPENSES_KEYS_LETTER =     charAfter('H',  INSTERTED_COLUMNS_NUMBER)
const MONTHLY__ESTIMATED_EXPENSES_VALUES_LETTER =   charAfter('I',  INSTERTED_COLUMNS_NUMBER)
 
const MONTHLY__ACTUAL_EXPENSES_KEYS_LETTER =        charAfter('L',  INSTERTED_COLUMNS_NUMBER)
const MONTHLY__ACTUAL_EXPENSES_VALUES_LETTER =      charAfter('M',  INSTERTED_COLUMNS_NUMBER)

const MONTHLY__ESTIMATED_INCOMES_KEYS_RANGE_TEXT =  getMonthlyKeysRangeText(MONTHLY__ESTIMATED_INCOMES_KEYS_LETTER)
const MONTHLY__ACTUAL_INCOMES_RANGE_TEXT =          getMonthlyOperationTypeRangeText(MONTHLY__ACTUAL_INCOMES_KEYS_LETTER, MONTHLY__ACTUAL_INCOMES_VALUES_LETTER)
const MONTHLY__ESTIMATED_EXPENSES_KEYS_RANGE_TEXT = getMonthlyKeysRangeText(MONTHLY__ESTIMATED_EXPENSES_KEYS_LETTER)
const MONTHLY__ACTUAL_EXPENSES_RANGE_TEXT =         getMonthlyOperationTypeRangeText(MONTHLY__ACTUAL_EXPENSES_KEYS_LETTER, MONTHLY__ACTUAL_EXPENSES_VALUES_LETTER)

// TODO refactor, use POS
// offsets
const MONTHLY__IS_PLANNED_OFFSET_FROM_ESTIMATED_EXPENSES_KEYS = -1

const MONTHLY__ESTIMATED_INCOMES_VALUES_OFFSET_FROM_ESTIMATED_INCOMES_KEYS = 1
const MONTHLY__ESTIMATED_EXPENSES_VALUES_OFFSET_FROM_ESTIMATED_EXPENSES_KEYS = MONTHLY__ESTIMATED_INCOMES_VALUES_OFFSET_FROM_ESTIMATED_INCOMES_KEYS


// aux
const MONTHLY__AUX_DATA_ROW_OFFSET_INCLUDING_HEADER = 219
const MONTHLY__AUX_DATA_ROW_OFFSET = 220
const MONTHLY__AUX_RANGE_START_LETTER = charAfter('A', INSTERTED_COLUMNS_NUMBER)
const MONTHLY__AUX_RANGE_END_LETTER = charAfter('C', INSTERTED_COLUMNS_NUMBER)

const MONTHLY__AUX_RANGE_INCLUDING_HEADER_TEXT = MONTHLY__AUX_RANGE_START_LETTER + MONTHLY__AUX_DATA_ROW_OFFSET_INCLUDING_HEADER.toString() + ":" + MONTHLY__AUX_RANGE_END_LETTER + DATA_ROWS_UPPER_LIMIT
const MONTHLY__AUX_RANGE_TEXT = MONTHLY__AUX_RANGE_START_LETTER + MONTHLY__AUX_DATA_ROW_OFFSET.toString() + ":" + MONTHLY__AUX_RANGE_END_LETTER + DATA_ROWS_UPPER_LIMIT

