const MONTHLY__ESTIMATED_INCOMES_CATEGORY_LETTER =      charAfter('A',  INSTERTED_COLUMNS_NUMBER)
const MONTHLY__ESTIMATED_INCOMES_AMOUNT_LETTER =        charAfter('B',  INSTERTED_COLUMNS_NUMBER)
const MONTHLY__ESTIMATED_INCOMES_RANGE_TEXT =           getMonthlyOperationTypeRangeText(
                                                          MONTHLY__ESTIMATED_INCOMES_CATEGORY_LETTER, 
                                                          MONTHLY__ESTIMATED_INCOMES_AMOUNT_LETTER
                                                        )
  
const MONTHLY__ACTUAL_INCOMES_CATEGORY_LETTER =         charAfter('D',  INSTERTED_COLUMNS_NUMBER)
const MONTHLY__ACTUAL_INCOMES_AMOUNT_LETTER =           charAfter('E',  INSTERTED_COLUMNS_NUMBER)
  
const MONTHLY__ESTIMATED_EXPENSES_IS_GUARANTED_LETTER = charAfter('G',  INSTERTED_COLUMNS_NUMBER)
const MONTHLY__ESTIMATED_EXPENSES_CATEGORY_LETTER =     charAfter('H',  INSTERTED_COLUMNS_NUMBER)
const MONTHLY__ESTIMATED_EXPENSES_AMOUNT_LETTER =       charAfter('I',  INSTERTED_COLUMNS_NUMBER)
const MONTHLY__ESTIMATED_EXPENSES_COMMENT_LETTER =      charAfter('J',  INSTERTED_COLUMNS_NUMBER)

const MONTHLY__ESTIMATED_EXPENSES_START_LETTER =        MONTHLY__ESTIMATED_EXPENSES_IS_GUARANTED_LETTER
const MONTHLY__ESTIMATED_EXPENSES_END_LETTER =          MONTHLY__ESTIMATED_EXPENSES_COMMENT_LETTER
const MONTHLY__ESTIMATED_EXPENSES_RANGE_TEXT =          getMonthlyOperationTypeRangeText(
                                                          MONTHLY__ESTIMATED_EXPENSES_START_LETTER, 
                                                          MONTHLY__ESTIMATED_EXPENSES_END_LETTER
                                                        ) 

const MONTHLY__ACTUAL_EXPENSES_KEYS_LETTER =        charAfter('L',  INSTERTED_COLUMNS_NUMBER)
const MONTHLY__ACTUAL_EXPENSES_VALUES_LETTER =      charAfter('M',  INSTERTED_COLUMNS_NUMBER)



const MONTHLY__ESTIMATED_INCOMES_KEYS_RANGE_TEXT =  getMonthlyKeysRangeText(MONTHLY__ESTIMATED_INCOMES_CATEGORY_LETTER)
const MONTHLY__ACTUAL_INCOMES_RANGE_TEXT =          getMonthlyOperationTypeRangeText(MONTHLY__ACTUAL_INCOMES_CATEGORY_LETTER, MONTHLY__ACTUAL_INCOMES_AMOUNT_LETTER)
const MONTHLY__ESTIMATED_EXPENSES_KEYS_RANGE_TEXT = getMonthlyKeysRangeText(MONTHLY__ESTIMATED_EXPENSES_CATEGORY_LETTER)
const MONTHLY__ACTUAL_EXPENSES_RANGE_TEXT =         getMonthlyOperationTypeRangeText(MONTHLY__ACTUAL_EXPENSES_KEYS_LETTER, MONTHLY__ACTUAL_EXPENSES_VALUES_LETTER)

// TODO refactor, use POS
// offsets
const MONTHLY__ESTIMATED_INCOMES_CATEGORY_POS = 0
const MONTHLY__ESTIMATED_INCOMES_AMOUNT_POS =   1

const MONTHLY__ESTIMATED_EXPRENSES_IS_GUARANTED_POS = 0
const MONTHLY__ESTIMATED_EXPRENSES_CATEGORY_POS =     1
const MONTHLY__ESTIMATED_EXPRENSES_AMOUNT_POS =       2
const MONTHLY__ESTIMATED_EXPRENSES_COMMENT_POS =      3


const MONTHLY__ESTIMATED_IS_PLANNED_FROM_EXPENSES_KEYS_OFFSET =   -1
const MONTHLY__ESTIMATED_IS_PLANNED_FROM_EXPENSES_VALUES_OFFSET = -2

const MONTHLY__ESTIMATED_INCOMES_VALUES_FROM_KEYS_OFFSET = 1
const MONTHLY__ESTIMATED_EXPENSES_VALUES_FROM_KEYS_OFFSET = MONTHLY__ESTIMATED_INCOMES_VALUES_FROM_KEYS_OFFSET


// aux
const MONTHLY__AUX_DATA_ROW_OFFSET_INCLUDING_HEADER = 219
const MONTHLY__AUX_DATA_ROW_OFFSET = 220
const MONTHLY__AUX_RANGE_START_LETTER = charAfter('A', INSTERTED_COLUMNS_NUMBER)
const MONTHLY__AUX_RANGE_END_LETTER = charAfter('C', INSTERTED_COLUMNS_NUMBER)

const MONTHLY__AUX_RANGE_INCLUDING_HEADER_TEXT = MONTHLY__AUX_RANGE_START_LETTER + MONTHLY__AUX_DATA_ROW_OFFSET_INCLUDING_HEADER.toString() + ":" + MONTHLY__AUX_RANGE_END_LETTER + DATA_ROWS_UPPER_LIMIT
const MONTHLY__AUX_RANGE_TEXT = MONTHLY__AUX_RANGE_START_LETTER + MONTHLY__AUX_DATA_ROW_OFFSET.toString() + ":" + MONTHLY__AUX_RANGE_END_LETTER + DATA_ROWS_UPPER_LIMIT

